JFLAGS= -g -d ../../class
JC=javac


#ArrayMethods.class: ArrayMethods.java
#	$(JC) $(JFLAGS) ArrayMethods.java 

TestArrayMethods.class: TestArrayMethods.java
	$(JC) $(JFLAGS) TestArrayMethods.java 
