JFLAGS= -g -d ../class
JC=javac

#HelloWorld.class: HelloWorld.java
#	$(JC) $(JFLAGS) HelloWorld.java 

PrimitiveDataType.class: PrimitiveDataType.java
	$(JC) $(JFLAGS) PrimitiveDataType.java 

#EvenNumber.class: EvenNumber.java
#	$(JC) $(JFLAGS) EvenNumber.java 

#Factorial.class: Factorial.java
#	$(JC) $(JFLAGS) Factorial.java 
